#!/usr/bin/env bash

set -e

psql postgres -c "DROP DATABASE IF EXISTS datagol_test"
psql postgres -c "DROP USER IF EXISTS datagol_test"
createuser -d datagol_test
createdb -E utf8 -e -w -O datagol_test datagol_test
